# Generated by Django 5.2.5 on 2025-10-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('student_age', models.IntegerField()),
                ('student_data_birth', models.DateField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_address', models.TextField()),
            ],
        ),
    ]
