# Generated by Django 5.2.5 on 2025-10-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_remove_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_data_birth',
            new_name='student_date_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
